### ISSUE TITLE
Idea: Scrap the web runtime and add a Node runtime

### ISSUE THREAD

**Issue by bradjc** [lab11/accessors#21]
Although I hate that I had this idea, but the convergence of cross-origin-garbage, swarmboxes, and this crazy standards idea has got me thinking that we should drop running accessors in the browser and run them all server side. The browser just uses the standard interface (not sure how it learns about devices and whatnot yet) to the server (basically what we are doing now since we proxy everything), and the server relays those messages (or uses an accessor) to control the device.

The cool perk here is the server can be the global one or the one running on Your Local SwarmBox (tm) and the browser will work the same.

**Comment by brghena** [comment]
Would you still actually ship code in the command-line and Android cases?

**Comment by ppannuto** [comment]
We still ship code in all cases really. The accessor _runtime_ would be on
the SwarmBox, but the accessor itself would be in the cloud. Code would
have to get shipped to the SwarmBox on-demand.
