### ISSUE TITLE
Exception in host-server

### ISSUE THREAD

**Issue by bradjc** [lab11/accessors#42]
![accessors io-error](https://cloud.githubusercontent.com/assets/1467890/8269800/664a39fc-1789-11e5-9c82-b85faa5896ce.PNG)

couldn't copy and paste from that terminal for some reason

**Comment by ppannuto** [comment]
Is this on the new branch or the old?

Can you turn logging to debug? That trace isn't very useful.

Ding ding. 10k feet apparently.

**Comment by bradjc** [comment]
Old.

**Comment by ppannuto** [comment]
Too much has changed in the new branch. If this is still an issue with new stuff, reopen.
